### ISSUE TITLE
Hi - привет

### ISSUE THREAD

**Issue by amirlime** [SNIPPIK/WatKLOK#19]
Ты можешь помочь мне с запуском
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/20638b54-f7ab-418d-bdd2-686c16d0edad)

**Comment by SNIPPIK** [comment]
Привет, отсутвует папка node_build.
Скорее всего 5 шаг был выполнен не правильно!

**Comment by amirlime** [comment]
Всмысле я все сделал все ровно не может

**Comment by SNIPPIK** [comment]
1. Устанавливаем все зависимости `npm i`
2. Выполняем сборку `npm i -g typescript`
3. Настраиваем конфиг .env в директории `node_build`

**Comment by amirlime** [comment]
Настраиваем конфиг .env в директории node_build это как извини за тупые вопросы

**Comment by SNIPPIK** [comment]
> Настраиваем конфиг .env в директории node_build это как извини за тупые вопросы

https://github.com/SNIPPIK/WatKLOK#%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-env-%D1%84%D0%B0%D0%B9%D0%BB

**Comment by amirlime** [comment]
можем ли вы по Дискорд написать

**Comment by SNIPPIK** [comment]
> > Настраиваем конфиг .env в директории node_build это как извини за тупые вопросы
> 
> https://github.com/SNIPPIK/WatKLOK#%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-env-%D1%84%D0%B0%D0%B9%D0%BB

Ссылка на [env файл](https://github.com/SNIPPIK/WatKLOK/blob/nightly/.env)
Его необходимо создать в `node_build` и настроить 
1. Необходимо заполнить параметры token (необходим только token.discord)
2. Заполнить параметры progress, button, loading

**Comment by amirlime** [comment]
Извини можно по понятней как  Его необходимо создать в **node_build и настроить**

**Comment by SNIPPIK** [comment]
RU
- В скачанном образе уже идет `.env` файл скопируй его в `node_build` и затем пропиши необходимые данные такие как token

EN
- The downloaded image already has an `.env` file, copy it to `node_build` and then write down the necessary data such as token


https://github.com/SNIPPIK/WatKLOK/assets/55327334/d2fb653b-5efd-47ce-b7d2-7ba2c109e92c

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/db453f04-14ee-450e-b511-c6a886b9f05e)

**Comment by amirlime** [comment]
вот такая ошибка

**Comment by SNIPPIK** [comment]
Используй npm run build

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/7e440292-480c-402f-9e60-5a620a03c5bf)
Это так и должно быть ?

**Comment by SNIPPIK** [comment]
# Эта ошибка связана с измененим ветки
- Надо изменить
`filters.url`, `image.not`, `image.currentPlay`
`WatKLOK/main` изменить на `WatKLOK/nightly`

Рекомендую использовать [0.4.0-pre2](https://github.com/SNIPPIK/WatKLOK/releases/tag/0.0.4-pre.2)

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/a9a5a5d8-aa40-45dd-943c-c1f2c020b892)
а можно прогресс бар Плюс
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/fae5d73c-1c45-48bf-b055-f25209c98117)

**Comment by SNIPPIK** [comment]
> ![image](https://private-user-images.githubusercontent.com/122648967/318288707-a9a5a5d8-aa40-45dd-943c-c1f2c020b892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDU5MzAsIm5iZiI6MTcxMTkwNTYzMCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjg4NzA3LWE5YTVhNWQ4LWFhNDAtNDVkZC05NDNjLWMxZjJjMDIwYjg5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNzIwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTgxNDZkMGFhNDBhZTI5ZjhiNzI5ZDM3M2UzNjFhMDUwYTJmYWUwMGM3OTlkYjc1NmEzMGRhOWRiYTRjYWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Xi5TwgOLXMX2UwLhWN-120KqlWsOBN9jYXNl8D-Kgk) а можно прогресс бар Плюс ![image](https://private-user-images.githubusercontent.com/122648967/318288728-fae5d73c-1c45-48bf-b055-f25209c98117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDU5MzAsIm5iZiI6MTcxMTkwNTYzMCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjg4NzI4LWZhZTVkNzNjLTFjNDUtNDhiZi1iMDU1LWYyNTIwOWM5ODExNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNzIwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWNiMmRjMjgyNmFiOWM2YmQyMTAxZjA2NjlmZmE3M2NlMWNlZjRlNDNmZWFlYWNjOTk0NDBkOGMxZmQzNzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jbkpYEkMgmKxKah3xCR_YbvyCU9CmT6PK9iVa9xtIO8)


Как решить проблему с прогресс баром, нужно это заменить на свои смайлы или символы
![image](https://github.com/SNIPPIK/WatKLOK/assets/55327334/34525b58-4f93-4860-90ec-1c80113f7e19)

Так-же это отвечает за кнопки под сообщение о текущем треке
![image](https://github.com/SNIPPIK/WatKLOK/assets/55327334/bfdd864d-aae3-4c25-ac8c-d6b278b6f67e)

Я могу помочь все это настроить

**Comment by SNIPPIK** [comment]
В системе присутствует FFmpeg?

![image](https://github.com/SNIPPIK/WatKLOK/assets/55327334/e33caed2-0dd5-451b-8488-359e56dd34e3)

**Comment by amirlime** [comment]
все работает но можно progress bar

**Comment by SNIPPIK** [comment]
> все работает но можно progress bar

На символах 
Измени эти данные в `node_build/.env`
```css
progress.bottom="⚪️"
progress.empty.left="-"
progress.empty.right="-"
progress.empty.center="-"
progress.not_empty.left="-"
progress.not_empty.right="-"
progress.not_empty.center="-"
```

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/c6a4502d-2a58-411c-9200-35781ba84909)
вот так же надо ?

**Comment by SNIPPIK** [comment]
> ![image](https://private-user-images.githubusercontent.com/122648967/318289555-c6a4502d-2a58-411c-9200-35781ba84909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDY4NjQsIm5iZiI6MTcxMTkwNjU2NCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjg5NTU1LWM2YTQ1MDJkLTJhNTgtNDExYy05MjAwLTM1NzgxYmE4NDkwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNzM2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjMwNzMxZDMwYmRkNGZiMzYyZDQwNTczOTEzZjdjNzg5NjJkYzg1ODU1ODcyZDA1ODA4ZjRjYjQ4Mzg0MzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.veF_4UXYuj7x-QE93CeimpKSDfINbLEPxSsy0Co7veA) вот так же надо ?

Да но надо указавыть путь вместе c ffmpeg
Пример: `"C:\Windows\ffmpeg.exe"`

**Comment by amirlime** [comment]
погоди но у меня нету ffmpeg.exe

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/ed986dfc-5e91-4ee5-8099-fc810a3e8453)

**Comment by SNIPPIK** [comment]
А это надо собирать

Вот [готовый образ](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2024-03-31-17-28/ffmpeg-n6.1.1-31-gaa5e6017a5-win64-gpl-6.1.zip)

**Comment by amirlime** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/4350c496-12ce-4baa-b0cd-054ab3c081c6)
 не работает
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/69ff1f4f-ee03-4324-a512-d49b51f19fd1)

**Comment by amirlime** [comment]
и ещё вот ошибка 
![image](https://github.com/SNIPPIK/WatKLOK/assets/122648967/9bb5d14c-deef-4615-89ea-a9426528bb4a)

**Comment by SNIPPIK** [comment]
> и ещё вот ошибка ![image](https://private-user-images.githubusercontent.com/122648967/318303747-9bb5d14c-deef-4615-89ea-a9426528bb4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5MzgsIm5iZiI6MTcxMTkzNDYzOCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4MzAzNzQ3LTliYjVkMTRjLWRlZWYtNDYxNS04OWVhLWE5NDI2NTI4YmI0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDI0ZmMzMjVlOGNlNjE3YzM1YmRhNjRmZTkzMTNjZmUyMzA0MTFhYmU0NDRkYWY0ZjgxODdlOTE3OTMwYzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g6eYS7x5XIRrm10EiplZQgJvNxXCBE5881bj1TrZeV8)

Это была простая ошибка брандмауэра.
Голосовой чат Discord использует udp-порты между 45000 и 60000

**Comment by SNIPPIK** [comment]
> ![image](https://private-user-images.githubusercontent.com/122648967/318298644-4350c496-12ce-4baa-b0cd-054ab3c081c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5MzgsIm5iZiI6MTcxMTkzNDYzOCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjk4NjQ0LTQzNTBjNDk2LTEyY2UtNGJhYS1iMGNkLTA1NGFiM2MwODFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmQ4ZDMwZWZiNjQ1MTU0MzY4NjMwZjRjYzViNDY2NGQ0NjNjNGE1MTJkYmM4Y2VlMDJkOWFhOTg4ODMyNDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sxqXP36HteMszVZfX7QGdy1Jbpw2FE3X_3mfbtUIOOM) не работает ![image](https://private-user-images.githubusercontent.com/122648967/318298655-69ff1f4f-ee03-4324-a512-d49b51f19fd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5MzgsIm5iZiI6MTcxMTkzNDYzOCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjk4NjU1LTY5ZmYxZjRmLWVlMDMtNDMyNC1hNTEyLWQ0OWI1MWYxOWZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzY1ZTRhZjdjYmRmYzUzNzJjZDNiNjQyNTU0NDI3OWQ1MDRlODhjODc4MGExYWE3NDc0YjIzY2ZhODIxYjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nD0TCv_BHFPV3ePYnjeSh4PK8dtpv02GTq6o3cE_JUw)

Вот это уже странно

**Comment by SNIPPIK** [comment]
Лучше используй [`последнюю версию`](https://github.com/SNIPPIK/WatKLOK/releases/tag/0.0.4-b)
[0.0.3](https://github.com/SNIPPIK/WatKLOK/releases/tag/0.0.3) я выпустил 27.02.24, так что хз что там еще могло сломаться за это время

**Comment by SNIPPIK** [comment]
> > ![image](https://private-user-images.githubusercontent.com/122648967/318298644-4350c496-12ce-4baa-b0cd-054ab3c081c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5MzgsIm5iZiI6MTcxMTkzNDYzOCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjk4NjQ0LTQzNTBjNDk2LTEyY2UtNGJhYS1iMGNkLTA1NGFiM2MwODFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmQ4ZDMwZWZiNjQ1MTU0MzY4NjMwZjRjYzViNDY2NGQ0NjNjNGE1MTJkYmM4Y2VlMDJkOWFhOTg4ODMyNDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sxqXP36HteMszVZfX7QGdy1Jbpw2FE3X_3mfbtUIOOM) не работает ![image](https://private-user-images.githubusercontent.com/122648967/318298655-69ff1f4f-ee03-4324-a512-d49b51f19fd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5MzgsIm5iZiI6MTcxMTkzNDYzOCwicGF0aCI6Ii8xMjI2NDg5NjcvMzE4Mjk4NjU1LTY5ZmYxZjRmLWVlMDMtNDMyNC1hNTEyLWQ0OWI1MWYxOWZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzY1ZTRhZjdjYmRmYzUzNzJjZDNiNjQyNTU0NDI3OWQ1MDRlODhjODc4MGExYWE3NDc0YjIzY2ZhODIxYjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nD0TCv_BHFPV3ePYnjeSh4PK8dtpv02GTq6o3cE_JUw)
> 
> Вот это уже странно

По цвету Embed это трек с youtube, я обновлял расшифровщик поскольку тот не работает
![image](https://github.com/SNIPPIK/WatKLOK/assets/55327334/5a5e71b1-90e4-4640-899a-e7b949c30fe5)

**Comment by amirlime** [comment]
А ты можешь добавить команды там replay Lyrics bassboost и 24/7

**Comment by SNIPPIK** [comment]
> А вы можешь добавить команды там replay Lyrics bassboost и 24/7

Replay - /player control replay
Lyrics - пока в слишком сыром виде, его нету в проде
bassboost - /player filter bass
24/7 - будет только когда я допилю систему live эфиров

**Comment by SNIPPIK** [comment]
![image](https://github.com/SNIPPIK/WatKLOK/assets/55327334/4fc1bada-763a-43e3-81eb-6a2b70d7aa69)
